include:
  - project: "the-microservice-dungeon/devops-team/common-ci-cd"
    ref: "main"
    file:
      - "helm/package-publish.yaml"
      - "container/image-dockerfile-publish.yaml"

stages:
  - build_container_push
  - helm

variables:
  PATH_TO_CHART: "helm-chart"
  CHART_NAME: "player-name" # ! TODO: replace with your player-name
  CI_MSD_CONTAINER_REGISTRY: "registry.gitlab.com/the-microservice-dungeon/devops-team/msd-image-registry/player-name" # ! TODO: replace player-name with your player-name


# build stage (build from Dockerfile and push to msd registry, access token is needed)
container-image-publish:
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
    - if: '$CI_PIPELINE_SOURCE == "web"'
      when: always

# build and push helm chart to our registry (no access token is needed)
helm-package-publish:
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
      changes:
        - ${PATH_TO_CHART}/**/*
    - if: '$CI_PIPELINE_SOURCE == "web"'
      when: always

