name: baba-player
replicas: 1

loadBalancerNodePort: 31090

registry:
  secretName: baba-player-secret

image:
  name: "registry.gitlab.com/24coding/team-one-java-springboot"
  tag: "latest"
  imagePullPolicy: "Always"

serviceName: "baba-player"

lbTargetPort: 8090
port: 8080
lbNodePort: 31090

env:
  DATA_ENDPOINT_PORT: "8080"
  DATA_ENDPOINT_SECONDARY_PORT: "8090"
  GAME_HOST: "http://game-service.game"
  GAME_PORT: "8080"
  RABBITMQ_USERNAME: "admin"
  RABBITMQ_PASSWORD: "admin"
  RABBITMQ_HOST: "rabbitmq-service.rabbitmq"
  RABBITMQ_PORT: "5672"
  PLAYER_NAME: "baba-player"
  PLAYER_EMAIL: "big-baba-bubu-baba-playerplayer@example.com"
  DEV_MODE: false  # Assuming this is meant to be a boolean value, not a string.

ingress:
  enabled: true # True if you run the player on the cluster, false if you run it locally in minikube
  hostname: baba-player.goedel.debuas.de
  path: /
  classname: traefik
