name: "player-monte"
replicas: 1
image:
  name: "registry.gitlab.com/the-microservice-dungeon/player-teams/player-monte"
  tag: "latest"
  imagePullPolicy: "Always"
serviceName: "player-monte"
port: 8999
lbNodePort: 31090
env:
  - name: GAME_HOST
    value: "http://game-service.game:8080"
  - name: RABBITMQ_USERNAME
    value: "admin"
  - name: RABBITMQ_PASSWORD
    value: "admin"
  - name: RABBITMQ_HOST
    value: "rabbitmq-service.rabbitmq"
  - name: RABBITMQ_PORT
    value: "5672"

ingress:
  enabled: true
  hostname: player-monte.dungeon-space.de
  path: /
