name: big_baba_bubu_player
replicas: 1

loadBalancerNodePort: 31090

image:
  name: "registry.gitlab.com/24coding/team-one-java-springboot"
  tag: "latest"
  imagePullPolicy: "Always"
serviceName: "24coding/team-one-java-springboot"

lbTargetPort: 8090
port: 8080
lbNodePort: 31090

env:
  DATA_ENDPOINT_PORT: "8090"
  GAME_HOST: "http://game-service.game"
  GAME_PORT: "8080"
  RABBITMQ_USERNAME: "admin"
  RABBITMQ_PASSWORD: "admin"
  RABBITMQ_HOST: "rabbitmq-service.rabbitmq"
  RABBITMQ_PORT: "5672"
  PLAYER_NAME: "big_baba_bubu_player"
  PLAYER_EMAIL: "big_baba_bubu_player@example.com"
  DEV_MODE: "false"

ingress:
  enabled: true # True if you run the player on the cluster, false if you run it locally in minikube
  hostname: big_baba_bubu_player.goedel.debuas.de
  path: /
  classname: traefik

