name: player-skeleton-java-springboot # ! TODO: Update to your player name
replicas: 1

loadBalancerNodePort: 31090

image:
  name: "registry.gitlab.com/the-microservice-dungeon/player-teams/skeletons/player-skeleton-java-springboot" #TODO: Change this to your image path
  tag: "latest"
  imagePullPolicy: "Always"
serviceName: "Player-Skeleton-Java-Springboot" #TODO: Change this to the name of your Player Application

port: 8080
targetPort: 8080

env:
  INTERNAL_ENDPOINT_PORT: "8080"  #TODO: Substitute with correct port that the backend listens on; EXTERNAL_ENDPOINT_PORT will be mapped on this port
  EXTERNAL_ENDPOINT_PORT: "8080"
  GAME_HOST: "http://game-service.game:8080"
  RABBITMQ_USERNAME: "admin"
  RABBITMQ_PASSWORD: "admin"
  RABBITMQ_HOST: "rabbitmq-service.rabbitmq"
  RABBITMQ_PORT: "5672"
  PLAYER_NAME: "Player-Skeleton-Java-Springboot" #TODO: Substitute with correct player name
  PLAYER_EMAIL: "Player-Skeleton-Java-Springboot@test.com" #TODO: Substitute with correct player email
  DEV_MODE: "false"

ingress:
  enabled: true # True if you run the player on the cluster, false if you run it locally in minikube
  hostname: player-skeleton-java-springboot.goedel.debuas.de #TODO: Change this to your ingress hostname, if you need one
  path: /
  classname: traefik

