server:
  port: 8099
dungeon:
  mode: "SINGLE" # either "SINGLE" (if you build a player based on this), or "MULTI" (to test the core services)
  singlePlayer:
    playerName: "Martina Musterfrau"
    playerEmail: "martina@musterfrau.de"
  multiPlayer:
    number: 25
  services:
    game: ${GAME_SERVICE}