spring:
  profiles:
    default: "mock"  # others are: prod
    active: "prod"
dungeon:
  numberOfPlayers: 5
  services:
    game: ${GAME_SERVICE}
  mock:
    game:
      gameId: "20165011-013d-4a11-a5a9-c64d22ea76ca"
      initialDelayUntilStart: 5 # in seconds; 0 means it starts in state "GAME_RUNNING"
      roundLength: 10 # in seconds



