apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "player-tom.fullname" . }}
  labels:
    {{- include "player-tom.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas | int }}
  selector:
    matchLabels:
      {{- include "player-tom.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "player-tom.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "player-tom.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.name }}:{{ .Values.image.tag | default .Chart.Version }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
          {{- range .Values.service.ports }}
          - name: {{ .name | lower }}
            containerPort: {{ .port }}
            protocol: {{ .protocol }}
            {{- end }}
          {{- if .Values.resources }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
          {{- if .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "player-tom.fullname" . }}
          {{- if .Values.env }}
          env:
          {{- toYaml .Values.env | nindent 12 }}
          {{- end }}
          volumeMounts:
            - mountPath: {{ .Values.logVol.mountPath }}
              name: {{ .Values.logVol.name }}
      volumes:
        - name: {{ .Values.logVol.name }}
          emptyDir:
            sizeLimit: {{ .Values.logVol.sizeLimit }}

