apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-deployment
  namespace: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: registry.gitlab.com/the-microservice-dungeon/player-teams/{{ .Chart.Name }}:latest
          imagePullPolicy: Always
          env:
            - name: GAME_HOST
              value: http://game-service.game:8080
            - name: RABBITMQ_HOST
              value: rabbitmq-service.rabbitmq
            - name: PLAYER_SERVER_PORT
              value: "8999"
            - name: LOGGING_LEVEL
              value: debug
          volumeMounts:
            - mountPath: /app/logs
              name: logs-volume
      volumes:
        - name: logs-volume
          emptyDir:
            sizeLimit: 500Mi
