apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}-deployment
  namespace: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.Name }}
  template:
    metadata:
      labels:
        app: {{ .Values.Name }}
    spec:
      containers:
        - name: {{ .Values.Name }}
          {{- if .Values.image.tag }}
          image: {{ .Values.image.name }}:{{ .Values.image.tag }}
          {{- else }}
          image: {{ .Values.image.name }}:latest
          {{- end }}
          imagePullPolicy: {{ .Values.image.imagePullPolicy }}
          env:
            - name: GAME_HOST
              value: {{ .Values.env.GAME_HOST }}
            - name: GAME_PORT
              value: {{ .Values.env.GAME_PORT }}
            - name: RABBITMQ_HOST
              value: {{ .Values.env.RABBITMQ_HOST }}
            - name: RABBITMQ_PORT
              value: {{ .Values.env.RABBITMQ_PORT }}
            - name: RABBITMQ_USERNAME
              value: {{ .Values.env.RABBITMQ_USERNAME }}
            - name: RABBITMQ_PASSWORD
              value: {{ .Values.env.RABBITMQ_PASSWORD }}
            - name: DATA_ENDPOINT_PORT
              value: {{ .Values.env.DATA_ENDPOINT_PORT  }}
            - name: LOGGING_LEVEL
              value: {{ .Values.env.LOGGING_LEVEL }}
          volumeMounts:
            - mountPath: /app/logs
              name: logs-volume
      volumes:
        - name: logs-volume
          emptyDir:
            sizeLimit: 500Mi
