apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.registry.secretName }}"
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5naXRsYWIuY29tIjp7InVzZXJuYW1lIjoiRmlqb2xhQyIsInBhc3N3b3JkIjoiZ2xwYXQtcm9LNkw2Qk5Mdmp4YzNLeXBlanIiLCJlbWFpbCI6ImZpam9sYS5jenlib3Jza2lAdHV0YW5vdGEuY29tIn19fQ==