apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}-service
spec:
  selector:
    app: {{ .Values.Name }}
  ports:
    - protocol: TCP
      port: {{ .Values.env.DATA_ENDPOINT_PORT  | int }}
      targetPort: {{ .Values.env.DATA_ENDPOINT_PORT  | int }}

