apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
spec:
  selector:
    app: {{ .Values.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.env.EXTERNAL_ENDPOINT_PORT | int }}
      targetPort: {{ .Values.env.INTERNAL_ENDPOINT_PORT | int }}

