apiVersion: v1
kind: Service
metadata:
  name: {{ include "player-tom.fullname" . }}
  labels:
    {{- include "player-tom.labels" . | nindent 4 }}
spec:
  {{- range .Values.service.ports }}
  type: {{ .type }}
  ports:
    - port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: {{ .protocol }}
      name: {{ .name }}
  {{- end }}
  selector:
  {{- include "player-tom.selectorLabels" . | nindent 4 }}
